---
Title: Diagrama classes Usuaris
---

classDiagram
    class Usuari {
        - NIF : str
        - nom : str
        - cognoms : str
        - correu : str
        - contrasenya : str
    }
    class Client{
        - telefon : int
        - postal_adress : str
    }
    class PersonalShopper{
        - data_alta : str
        - clients_assignats : list[str]
    }
    %%Canvis de la classe Producte de l'exercici anterior: se li ha afegit l'atribut "revisions"
    class Producte{
        + revisions : list 
    }
    
    Usuari <|-- PersonalShopper
    Usuari <|-- Client
    PersonalShopper o-- Client  
    

    PersonalShopper: +Donar_alta()
    Client: +Donar_alta()
    Client: +Fer_comanda()