---
title: Diagrama Classes Catàleg
---

classDiagram
    class Secció {
        + nom : String
        + descripció : String
    }
    class Subsecció {
        + nom : Strring
        + descripció : String
    }
    class Marca {
        + nom : String
        + descripció : String
    }
    class Model {
        + nom : String
        + descripció : String
    }
    class Producte {
        + nom : String
        + preu : Integer
        + descripció : String
        + disponibilitat
    }

Secció "1" *-- "1..*" Subsecció
Subsecció "1" *-- "1..*" Producte
Marca "1" --> "1..*" Model
Model "1" *-- "1..*" Producte