sequenceDiagram
    participant C as Client
    participant S as Sistema
    participant PS as PersonalShopper
    C->>S: Seleccionar l'opció "Fer demanat"
    activate PS
    S->>PS: Avisar que el client vol fer un demanat
    PS->>S: Seleccionar les 5 peces
    PS->>S: Agregar una nota sobre com combinar les peces
    PS->>S: Afegir fitxes amb looks
    deactivate PS
    
    alt Primera comanda
        S->>C: Assessorament gratuït
    else
        S->>C: Carregar 10€ a l'import per assessorament
    end
    loop Fins que es pagui correctament
        C->>S: Pagar l'import total
    end
    S->>C: Enviar comanda
    note over C, S: El client té 1 setmana per decidir-se
    C->>S: Seleccionar i retornar peces indesitjades
    alt El client es queda amb alguna peça
        S->>C: Descomptar els 10€ de l'assessorament
    end
    alt El client es queda amb 5 peces
        S->>C: Aplicar un 25% de descompte
    else El client ha decidit retornar alguna o totes les peces  
        C->>S: Respondre formulari de devolució
        C->>S: Retornar les peces no desitjades
    end
    
