sequenceDiagram
    participant C as Client
    participant S as Sistema
    C->>S: Seleccionar l'opció "Devolució producte"
    S->>S: Comprovar que el client hagi demanat i rebut una comanda
    loop Fins que el client confirmi les peces a retornar
        S->>C: Mostrar quines peces de roba pot retornar
        C->>S: Seleccionar peces que vulgui retornar
        S->>C: Mostrar les peces seleccionades
        C->>S: Confirmar o no les peces a retornar
    end
    loop Per cada peça seleccionada per retornar
        S->>C: Enviar formulari
        C->>S: Respondre formulari
        S->>S: Processar devolució
    end
    